name: docker tagged

on:
  push:
    tags:
    - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to HSDP Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.na1.hsdp.io
          username: ${{ secrets.HSDP_DOCKER_USERNAME }}
          password: ${{ secrets.HSDP_DOCKER_PASSWORD }}
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
      - name: Set output
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          echo ::set-output name=sha_short::$(git rev-parse --short HEAD)
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            GIT_COMMIT=${{ steps.vars.outputs.sha_short }}
          platforms: linux/amd64
          push: true
          tags: philipslabs/siderite:${{ steps.vars.outputs.tag }},docker.na1.hsdp.io/philipslabs/siderite:${{ steps.vars.outputs.tag }}
      -
        name: Build and push debian
        id: docker_build_debian
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile.debian
          build-args: |
            GIT_COMMIT=${{ steps.vars.outputs.sha_short }}
          platforms: linux/amd64
          push: true
          tags: philipslabs/siderite:debian-${{ steps.vars.outputs.tag }},docker.na1.hsdp.io/philipslabs/siderite:debian-${{ steps.vars.outputs.tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
